---

  - name: install asdf
    hosts: '*'
    become: true
    gather_facts: true
    vars:
      asdf_version: v0.4.3
      asdf_user: "{{ username }}"
      asdf_plugins:
        - name: erlang
        - name: elixir
        - name: nodejs
    vars_files:
      - "../vars/build-{{ ansible_os_family }}.yml"
      - "../vars/build-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    roles:
      - asdf
